apiVersion: v2
name: flux2-sync
type: application
version: 1.14.0
appVersion: 2.7.0
description: A Helm chart for flux2 GitRepository to sync with
sources:
  - https://github.com/fluxcd-community/helm-charts
annotations:
  artifacthub.io/changes: |
    - "[Chore]: Update App Version to upstream 2.7.0"
