{{- if .Values.sourceWatcher.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: source-watcher
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    control-plane: controller
    {{- with .Values.sourceWatcher.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  name: source-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-watcher
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.sourceWatcher.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: source-watcher
{{ with .Values.sourceWatcher.labels }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      automountServiceAccountToken: {{ .Values.sourceWatcher.serviceAccount.automount }}
      {{- if .Values.sourceWatcher.initContainers}}
      initContainers:
        {{- toYaml .Values.sourceWatcher.initContainers | nindent 8}}
      {{- end}}
      containers:
      - args:
        {{- if .Values.notificationController.create }}
        - --events-addr=http://notification-controller.$(RUNTIME_NAMESPACE).svc.{{ .Values.clusterDomain | default "cluster.local" }}.
        {{- end}}
        - --watch-all-namespaces={{ .Values.watchAllNamespaces }}
        - --log-level={{ .Values.logLevel | default "info" }}
        - --log-encoding=json
        - --enable-leader-election
        - --storage-path=/data
        - --storage-adv-addr=source-watcher.$(RUNTIME_NAMESPACE).svc.{{ .Values.clusterDomain | default "cluster.local" }}.
        {{- range .Values.sourceWatcher.container.additionalArgs }}
        - {{ . }}
        {{- end}}
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.sourceWatcher.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ template "template.image" .Values.sourceWatcher }}
        {{- if .Values.sourceWatcher.imagePullPolicy }}
        imagePullPolicy: {{ .Values.sourceWatcher.imagePullPolicy }}
        {{- else }}
        imagePullPolicy: IfNotPresent
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 8080
          name: http-prom
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{- with .Values.sourceWatcher.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.sourceWatcher.securityContext }}
        securityContext: {{ toYaml .Values.sourceWatcher.securityContext | nindent 10 }}
        {{- else }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        {{- end}}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
        {{- if .Values.sourceWatcher.volumeMounts }}
        {{- toYaml .Values.sourceWatcher.volumeMounts | nindent 8 }}
        {{- end}}
      {{- if .Values.sourceWatcher.priorityClassName }}
      priorityClassName: {{ .Values.sourceWatcher.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.sourceWatcher.podSecurityContext }}
      securityContext: {{ toYaml .Values.sourceWatcher.podSecurityContext | nindent 8 }}
      {{- else if not .Values.distro.openshift }}
      securityContext:
        fsGroup: 1337
      {{- end}}
      serviceAccountName: source-watcher-controller
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
      {{- if .Values.sourceWatcher.volumes }}
      {{- toYaml .Values.sourceWatcher.volumes | nindent 6 }}
      {{- end}}
      {{- with .Values.sourceWatcher.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sourceWatcher.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sourceWatcher.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
